version: '3.1'

services:
  dailyapp:
    container_name: daily.jar
    restart: always
    image: daily
    build: ./
    ports:
      - "2222:2222"
    networks:
      - daily_default
    depends_on:
      - "PostgreSQL"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://PostgreSQL:5432/daily_database
      SPRING_DATASOURCE_USERNAME: "postgres"
      SPRING_DATASOURCE_PASSWORD: "postgres"
      SPRING_JPA_HIBERNATE_DDL_AUTO: create

  PostgreSQL:
    container_name: postgres_db
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=daily_database

networks:
  daily_default:
    name: daily_default
    driver: bridge